name: Pull Request Lint Check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - staging

jobs:
  # TODO: Add any other checks and tests later
  eslint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint