name: Deploy on Staging/Preview (Vercel)
env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
  workflow_dispatch:
  push:
    branches:
      - staging

jobs:
  # TODO: Add any other checks and tests later
  eslint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
      
      - name: Build Project Artifacts
        run: vercel build --token=$VERCEL_TOKEN

      # Check Vercel file usage to ensure not exceeding the limits
      - name: Check Vercel File Usage
        run: |
          OUTPUT=$(du --inodes -d 5 .vercel/output)
          echo "$OUTPUT"
          LAST=$(echo "$OUTPUT" | tail -n 1)
          PERCENTAGE=$(echo "$LAST" | awk 'BEGIN {maxtotal=15000} { printf "%.2f%%", ($1/maxtotal*100) }')
          echo "Vercel file usage percentage" >> $GITHUB_STEP_SUMMARY
          echo "$PERCENTAGE" >> $GITHUB_STEP_SUMMARY
      
      - name: Deploy Project Artifacts to Vercel (Preview)
        run: |
          DEPLOY_URL=$(vercel deploy --prebuilt --token=$VERCEL_TOKEN --confirm)
          echo "Deployed URL: $DEPLOY_URL" >> $GITHUB_STEP_SUMMARY
          echo "::set-output name=deploy_url::$DEPLOY_URL"
      
      - name: Deployment Summary
        run: |
          echo "Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "Deployed URL: ${{ steps.deploy-prod.outputs.deploy_url }}" >> $GITHUB_STEP_SUMMARY
          echo "Vercel file usage percentage: $PERCENTAGE" >> $GITHUB_STEP_SUMMARY
          echo "Deployment completed successfully!" >> $GITHUB_STEP_SUMMARY